src/core/views.py
from flask import Blueprint,render_template,url_for,redirect
from flask_login import login_required
from werkzeug.utils import secure_filename
from src import app
from src.core.forms import Ejecutar,Seleccionar
import paramiko
import time
import os

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
HOST = '192.168.x.xxx'
USERNAME = 'xxx'
PASSWORD = 'xxx'


core = Blueprint('core',__name__)


@login_required
@core.route('/home/<string:user>')
def home(user):
    return render_template('home.html',user=user)

@login_required
@core.route('/ejecutar/comando', methods=['POST','GET'])
def comando():

    form = Ejecutar()

    if form.validate_on_submit():
        client.connect(HOST,username=USERNAME,password=PASSWORD)
        comando = form.comando.data

        stdin,stdout,stderr = client.exec_command(comando)

        print('ejecutando')
        print(stdin)
        print(stderr)

        #for line in stdout:
        #    print (line.strip('\n'))

        return render_template('stdout.html',form=form, stdin=stdin,stdout=stdout,stderr=stderr)

    return render_template('comando.html',form=form)

@login_required
@core.route('/terminal', methods=['POST','GET'])
def terminal():
    client.connect(HOST, username=USERNAME, password=PASSWORD)
    transport = client.get_transport()
    ssh_session = transport.open_session()
    ssh_session.get_pty()
    shell = ssh_session.invoke_shell()
    print(shell)

    return render_template('terminal.html',shell=shell)




@login_required
@core.route('/subir_archivo', methods=['POST','GET'])
def upload():
    form = Seleccionar()
    if form.validate_on_submit():
        print('copiando')
        basedir = os.path.abspath(os.path.dirname(__file__))
        file = form.upload_file.data

        filename = secure_filename(file.filename)

        file.save(basedir+'/uploads/'+ filename)
        client.connect(HOST, username=USERNAME, password=PASSWORD)
        ftp_client = client.open_sftp()
        ftp_client.put(basedir+'/uploads/'+filename, '/xx/xx/xxx/'+filename)
        ftp_client.close()

    return render_template('subir_archivo.html',form=form)



@login_required
@core.route('/parar',methods=['POST','GET'])
def parar():
    client.close()

    return render_template('home.html')

src/users/views.py
from flask import Blueprint,redirect,render_template,url_for,flash,session,current_app,request
from src.users.forms import LoginForm,RegisterForm,CambiarPassForm
from src.models import Users
from flask_login import login_user,logout_user
from src.decorators import requires_admin
from src import db
from flask_login import login_required
from src import login_manager
import os
from werkzeug.security import generate_password_hash

users = Blueprint('users',__name__)

@login_manager.user_loader
def load_user(user_id):
    return Users.query.get(user_id)


@users.route('/')
@users.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = Users.query.filter_by(username=username).first()
        if form.check_user(username) and user.check_password(password):
            login_user(user)
            print('sorete')
            session['username'] = user.username
            if session['username'] == os.environ.get('ADMIN'):
                next = request.args.get('next')
                if next == None or not next[0] == '/':
                    next = url_for('core.home', user=session['username'])
                    flash('Eres el administrador', 'dark')
                return redirect(next)
            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('core.home',user=session['username'])
                flash(f'Bienvenido {session["username"]}', 'info')
            return redirect(next)

        else:
            flash('Nombre de usuario o password incorrectos','warning')
            return render_template('login.html',form=form)
    return render_template('login.html',form=form)

@login_required #YOU HAVE TO COMMENT THIS TO REGISTER AN ADMIN
@requires_admin #YOU HAVE TO COMMENT THIS TO REGISTER AN ADMIN
@users.route('/register',methods=['GET','POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        user = Users(form.username.data,form.password.data)
        if form.check_user(user.username):
            flash('El nombre de usuario ya esta en uso','warning')
            return render_template('register.html',form=form)
        else:
            db.session.add(user)
            db.session.commit()
            flash('El usuario ha sido agregado satisfactoriamente','success')
            return redirect(url_for('.login'))
    return render_template('register.html',form=form)



@login_required
@users.route('/cambiarpass/<string:username>',methods=['GET','POST'])
def cambiarpass(username):

    form = CambiarPassForm()

    if form.validate_on_submit():
        user = Users.query.filter_by(username=username).first()
        old_password =  form.old_password.data

        if form.old_password.data == form.password.data:
            flash('El password nuevo no debe ser igual que el password viejo, porfavor intente denuevo.', 'danger')
            return redirect(url_for('core.home', user=session['username']))

        if user.check_password(old_password):
            Users.query.filter_by(username= username).update({Users.password_hash:generate_password_hash(form.password.data)
                                                              },synchronize_session=False)
            db.session.commit()
            flash('Password cambiado satisfactoriamente.','success')
            return redirect(url_for('core.home',user=session['username']))
        else:

            flash('El password viejo no es correcto, porfavor vuelva a intentarlo.','info')

    return render_template('cambiar_password.html',form=form)

@login_required 
@requires_admin 
@users.route('/delete/<int:userid>')
def delete(userid):
    user = Users.query.filter(Users.id == userid).first()
    db.session.delete(user)
    db.session.commit()
    flash('El usuario ha sido borrado', 'success')

    return redirect(url_for('.list'))

@login_required
@requires_admin
@users.route('/users_list')
def list():
    query = Users.query.filter(Users.username != os.environ.get('ADMIN'))
    return render_template('userslist.html',users=query)



@login_required
@users.route('/mensaje')
def mensaje():
    pass



@login_required
@users.route('/logout')
def logout():
    logout_user()
    flash(f'Chau {session["username"]}', 'primary')

    session['username'] = ''

    return redirect(url_for('.login'))

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>RaspControl|{% block title %} {% endblock title %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, men in messages %}

        <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
          <button type="button" class="fade close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>

            {{ men }}
        </div>
        {% endfor %}
    {% endif %}
  {% endwith %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  {% if current_user.is_authenticated %}

  <a class="navbar-brand" href="#">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    {% block username %}

    {{ session['username'] }}

    {% endblock username %}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{{ url_for('users.cambiarpass', username=session['username']) }}">Cambiar password</a>
          <a class="dropdown-item" href="#">Ver logs</a>
            {% if current_user.is_authenticated and session['username'] != config.ADMIN %}
          <a class="dropdown-item" href="#">Dejar un mensaje al administrador</a>
            {% endif %}
        </div>

</a>
  {% endif %}
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        {% if current_user.is_authenticated %}
        <a class="nav-link" href="{{ url_for('core.home',user=session['username']) }}">Home <span class="sr-only">(current)</span></a>
      </li>
        {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
      </li>
      <!-- YOU HAVE TO UNCOMMENT THIS FOR REGISTER THE ADMIN USER
         <li class="nav-item">
        <a class="nav-link" href="{{ url_for('users.register') }}">Registrar</a>
      </li>
        -->
        {% endif %}
        {% if current_user.is_authenticated and session['username'] == config.ADMIN  %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('users.register') }}">Registrar</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('users.list') }}">Borrar usuario</a>
      </li>
        {% endif %}
        {% if current_user.is_authenticated %}
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
      </li>
        {% endif %}

    </ul>
  </div>
</nav>
{% block content %}

{% endblock content %}
{% block terminal %}
{% endblock terminal %}

</body>
</html>

src/templates/cambiar_password.html
{% extends 'base.html' %}

{% block title %} Cambiar Password {% endblock title %}

{% block content %}

<div class="modal fade" id="modalRegisterForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <form method="post" action="{{ url_for('users.cambiarpass', username=session['username']) }}" name="RegisterForm">
  {{ form.hidden_tag() }}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Cambiar Password</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <div class="form-group">
        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          {{ form.old_password(type="password", id="orangeForm-pass", class="form-control validate") }}
          {{ form.old_password.label(for="orangeForm-pass") }}
        </div>
        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          {{ form.password(type="password", id="orangeForm-pass", class="form-control validate") }}
          {{ form.password.label(for="orangeForm-pass") }}
        </div>
        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          {{ form.password_confirm(type="password", id="defaultForm-pass", class="form-control validate") }}
          {{ form.password_confirm.label(for="orangeForm-pass") }}
        </div>
      </div>
      <div class="modal-footer d-flex justify-content-center">

          {{ form.submit(class="btn btn-deep-orange") }}

      </div>
    </div>
    </div>
  </div>
  </form>
</div>

<div class="text-center">
  <h1><a href="" class="btn btn-default btn-rounded mb-4" data-toggle="modal" data-target="#modalRegisterForm">CAMBIAR PASSWORD</a></h1>
</div>

{% endblock content %}

src/templates/comando.html
{% extends 'base.html' %}
{% block title %} comando {% endblock title %}

{% block content %}


   <form method="POST">
      {{ form.hidden_tag() }}
       <p>Comando especifico</p>
      {{ form.comando.label() }}
      {{ form.comando() }}
      {{ form.submit(class="btn btn-primary") }}
   <a href="{{ url_for('core.parar') }}" class="btn btn-danger">Parar</a>
   <a href="{{ url_for('core.terminal') }}" class="btn btn-danger">Abrir terminal(en desarrollo)</a>
    </form>
{% block stdout %}
{% endblock stdout %}

{% endblock content %}

src/templates/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock title %}

{% block content %}

<div class="card-deck">
  <div class="card">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">Ejecutar un comando en un servidor remoto</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">ej: $ls -la</small>
    </div>
   <a href="{{ url_for('core.comando') }}" class="btn btn-primary">Ejecutar comando</a>

  </div>

  <div class="card">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Subir Archivo</h5>
      <p class="card-text">Subir algun archivo al servidor remoto</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">upload</small>
    </div>
      <a href="{{ url_for('core.upload') }}" class="btn btn-primary">Subir script</a>
  </div>
  <div class="card">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">en desarrollo</h5>
      <p class="card-text">en desarrollo</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">en desarrollo</small>
    </div>
      <a href="#" class="btn btn-primary">en desarrollo</a>
  </div>
</div>

{% endblock content %}

src/templates/login.html
{% extends 'base.html' %}

{% block title %} Entrar {% endblock title %}

{% block content %}

<div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
    <form method="post" action="{{ url_for('users.login') }}" name="LoginForm">

  {{ form.hidden_tag() }}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Iniciar sesion</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <div class="md-form mb-5">
          <i class="fas fa-envelope prefix grey-text"></i>
          {{ form.username(type="text", id="orangeForm-name", class="form-control validate") }}
          {{ form.username.label(for="orangeForm-name") }}
        </div>

        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          {{ form.password(type="password", id="defaultForm-pass", class="form-control validate") }}
          {{ form.password.label(for="defaultForm-pass") }}
        </div>

      </div>
      <div class="modal-footer d-flex justify-content-center">
        {{ form.submit(class="btn btn-default") }}
      </div>
    </div>
  </div>
</form>
</div>

<div class="text-center">
  <h1><a href="" class="btn btn-default btn-rounded mb-4" data-toggle="modal" data-target="#modalLoginForm">INICIAR SESION</a></h1>
</div>


{% endblock content %}

src/templates/register.html
{% extends 'base.html' %}

{% block title %} Registrar usuario {% endblock title %}

{% block content %}

<div class="modal fade" id="modalRegisterForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <form method="post" action="{{ url_for('users.register') }}" name="RegisterForm">
  {{ form.hidden_tag() }}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Registrar Usuario</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <div class="form-group">
        <div class="md-form mb-5">
          <i class="fas fa-user prefix grey-text"></i>
          {{ form.username(type="text", id="orangeForm-name", class="form-control validate") }}
          {{ form.username.label(for="orangeForm-name") }}
        </div>
        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          {{ form.password(type="password", id="orangeForm-pass", class="form-control validate") }}
          {{ form.password.label(for="orangeForm-pass") }}
        </div>
        <div class="md-form mb-4">
          <i class="fas fa-lock prefix grey-text"></i>
          {{ form.password_confirm(type="password", id="defaultForm-pass", class="form-control validate") }}
          {{ form.password_confirm.label(for="orangeForm-pass") }}
        </div>
      </div>
      <div class="modal-footer d-flex justify-content-center">

          {{ form.submit(class="btn btn-deep-orange") }}

      </div>
    </div>
    </div>
  </div>
  </form>
</div>

<div class="text-center">
  <h1><a href="" class="btn btn-default btn-rounded mb-4" data-toggle="modal" data-target="#modalRegisterForm">REGISTRAR USUARIO</a></h1>
</div>

{% endblock content %}

src/templates/stdout.html
{% extends 'comando.html' %}

{% block stdout %}

<h1>-------------------------------</h1>
{% for line in stdout %}


<p>{{ line.strip('\n') }}</p>

{% endfor %}
<h1>-------------------------------</h1>

{% endblock stdout %}

src/templates/subir_archivo.html
{% extends 'base.html' %}
{% block title %} Subir Archivo {% endblock title %}

{% block content %}


   <form method="POST" enctype="multipart/form-data">
      {{ form.hidden_tag() }}
      {{ form.upload_file.label() }}
      {{ form.upload_file() }}
      {{ form.submit(class="btn btn-primary") }}
    </form>

{% endblock content %}

src/templates/terminal.html
{% extends 'base.html' %}

{% block terminal %}

<h1>-------------------------------</h1>
<h1>TERMINAL</h1>
<h1>-------------------------------</h1>

{% endblock terminal %}

src/templates/userslist.html
{% extends 'base.html' %}

{% block title %} Lista de Usuarios {% endblock title %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Borrar usuarios</h1>
    <p class="lead">Seleccione el usuario que desea borrar</p>
  </div>

{% for user in users %}
<div class="list-group">
  <a href="{{ url_for('users.delete', userid=user.id) }}" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">{{ user.username }}</h5>
      <small>3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small>Donec id elit non mi porta.</small>
  </a>
</div>
{% endfor %}

</div>
{% endblock content %}